/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.userController;
import Laporan.fungsiCetak;
import Model.userModel;
import Model.waktuModel;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import koneksi.konfigurasi;
import koneksi.tesKoneksi;

/**
 *
 * @author HPrmn
 */
public class awalView extends javax.swing.JFrame {

    /**
     * Creates new form awalView
     */
    public userModel um = new userModel();
    userController uc;
    public awalView() {
        initComponents();
        Locale local = new Locale("id","ID");
        Locale.setDefault(local);      
        uc = new userController(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        uc.aAwal();
        waktuModel wm = new waktuModel(this);
        wm.jamSekarang(waktu);
        tanggal.setText(wm.gettanggal());
        getdataKoneksi();
        
    }
    public void getdataKoneksi(){
        host.setText(koneksi.panel("DBHost"));
        port.setText(koneksi.panel("DBPort"));
        database.setText(koneksi.panel("DBDatabase"));
        username.setText(koneksi.panel("DBUsername"));
        password.setText(koneksi.panel("DBPassword"));
    }

    public void postdata(){
        this.isinip.setText(String.valueOf(um.getNip()));
        this.isinama.setText(um.getNama());
        this.isibagian.setText(um.getJabatan());
    }
    public void simpanKonfigurasi(){
        konfigurasi konf = new konfigurasi();
        konf.edit("DBHost", host.getText());
        konf.edit("DBPort", port.getText());
        konf.edit("DBDatabase", database.getText());
        konf.edit("DBUsername", username.getText());
        konf.edit("DBPassword", password.getText());
        getdataKoneksi();
    }
    public void editKonfigurasi(Boolean nama){
        host.setEnabled(nama);
        host.setEditable(nama);
        port.setEnabled(nama);
        port.setEditable(nama);
        database.setEnabled(nama);
        database.setEditable(nama);
        username.setEnabled(nama);
        username.setEditable(nama);
        password.setEnabled(nama);
        password.setEditable(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        isinip = new javax.swing.JLabel();
        isinama = new javax.swing.JLabel();
        isibagian = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        database = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        btn_konfigurasi = new javax.swing.JButton();
        teskoneksi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        dataPegawai = new javax.swing.JMenuItem();
        dataBarang = new javax.swing.JMenuItem();
        data_user = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        penjualan = new javax.swing.JMenuItem();
        detail_penjualan = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        barang = new javax.swing.JMenuItem();
        laporanPegawai = new javax.swing.JMenuItem();
        laporanUser = new javax.swing.JMenuItem();
        laporanPenjualan = new javax.swing.JMenuItem();
        menu4 = new javax.swing.JMenu();
        backupDB = new javax.swing.JMenuItem();
        restoreDB = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NIP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Jabatan");

        jLabel4.setText(":");

        jLabel5.setText(":");

        jLabel6.setText(":");

        isinip.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        isinip.setText("NIP");

        isinama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        isinama.setText("NAMA");

        isibagian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        isibagian.setText("BAGIAN");

        login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isinip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isibagian, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isinama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(isinip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(isinama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(isibagian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("APLIKASI PENJUALAN HANDPHONE");

        waktu.setFont(new java.awt.Font("Imprint MT Shadow", 1, 50)); // NOI18N
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        waktu.setText("jLabel8");

        tanggal.setFont(new java.awt.Font("Imprint MT Shadow", 1, 50)); // NOI18N
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal.setText("jLabel8");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Konfigurasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel8.setText("Host");

        jLabel9.setText("Port");

        jLabel10.setText("Database");

        jLabel11.setText("Username");

        jLabel12.setText("Password");

        password.setEditable(false);
        password.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        password.setEnabled(false);

        username.setEditable(false);
        username.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        username.setEnabled(false);

        database.setEditable(false);
        database.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        database.setEnabled(false);

        host.setEditable(false);
        host.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        host.setEnabled(false);

        port.setEditable(false);
        port.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        port.setEnabled(false);

        btn_konfigurasi.setText("EDIT");
        btn_konfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfigurasiActionPerformed(evt);
            }
        });

        teskoneksi.setText("Tes Koneksi");
        teskoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teskoneksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_konfigurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teskoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password)
                            .addComponent(host)
                            .addComponent(port, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(database, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(database, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_konfigurasi, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(teskoneksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waktu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(waktu)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setPreferredSize(new java.awt.Dimension(600, 50));

        menu1.setText("Data Master");

        dataPegawai.setText("Data Pegawai");
        dataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPegawaiActionPerformed(evt);
            }
        });
        menu1.add(dataPegawai);

        dataBarang.setText("Data Barang");
        dataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBarangActionPerformed(evt);
            }
        });
        menu1.add(dataBarang);

        data_user.setText("Data User");
        data_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_userActionPerformed(evt);
            }
        });
        menu1.add(data_user);

        jMenuBar1.add(menu1);

        menu2.setText("Transaksi");

        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        menu2.add(penjualan);

        detail_penjualan.setText("Detail Penjualan");
        detail_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_penjualanActionPerformed(evt);
            }
        });
        menu2.add(detail_penjualan);

        jMenuBar1.add(menu2);

        laporan.setText("Laporan");

        barang.setText("Data Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        laporan.add(barang);

        laporanPegawai.setText("Data Pegawai");
        laporanPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanPegawaiActionPerformed(evt);
            }
        });
        laporan.add(laporanPegawai);

        laporanUser.setText("Data User");
        laporanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanUserActionPerformed(evt);
            }
        });
        laporan.add(laporanUser);

        laporanPenjualan.setText("Penjualan");
        laporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanPenjualanActionPerformed(evt);
            }
        });
        laporan.add(laporanPenjualan);

        jMenuBar1.add(laporan);

        menu4.setText("Tools");

        backupDB.setText("Backup Database");
        backupDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupDBActionPerformed(evt);
            }
        });
        menu4.add(backupDB);

        restoreDB.setText("Restore Database");
        restoreDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreDBActionPerformed(evt);
            }
        });
        menu4.add(restoreDB);

        jMenuBar1.add(menu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        // TODO add your handling code here:
        penjualanView pv = new penjualanView();
        pv.getNipkasir().setText(this.isinip.getText());
        pv.getNamaKasir().setText(this.isinama.getText());
        pv.setVisible(true);
        
    }//GEN-LAST:event_penjualanActionPerformed

    private void data_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_userActionPerformed
        // TODO add your handling code here:
        new userView().setVisible(true);
    }//GEN-LAST:event_data_userActionPerformed

    private void dataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBarangActionPerformed
        // TODO add your handling code here:
        new barangView().setVisible(true);
    }//GEN-LAST:event_dataBarangActionPerformed

    private void dataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPegawaiActionPerformed
        // TODO add your handling code here:
        new pegawaiView().setVisible(true);
    }//GEN-LAST:event_dataPegawaiActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        if(login.getText().equals("LOGOUT")){
            System.out.println("keluar dari aplikasi");
            //menu1.setEnabled(false);
            uc.aAwal();
            login.setText("LOGIN");
        }else if(login.getText().equals("LOGIN")){
            System.out.println("Masuk");
            new loginView(this).setVisible(true);
            login.setText("LOGOUT");
        }
        
    }//GEN-LAST:event_loginActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
        new fungsiCetak("./src/laporan/dataBarang.jasper");
    }//GEN-LAST:event_barangActionPerformed

    private void laporanPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanPegawaiActionPerformed
        // TODO add your handling code here:
        new fungsiCetak("./src/laporan/dataPegawai.jasper");
    }//GEN-LAST:event_laporanPegawaiActionPerformed

    private void laporanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanUserActionPerformed
        // TODO add your handling code here:
        new fungsiCetak("./src/laporan/dataUser.jasper");
    }//GEN-LAST:event_laporanUserActionPerformed

    private void laporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanPenjualanActionPerformed
        // TODO add your handling code here:
        new fungsiCetak("./src/laporan/penjualansemua.jasper");
    }//GEN-LAST:event_laporanPenjualanActionPerformed

    private void detail_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_penjualanActionPerformed
        // TODO add your handling code here:
        new detailpenjualanView().setVisible(true);
    }//GEN-LAST:event_detail_penjualanActionPerformed

    private void btn_konfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfigurasiActionPerformed
        // TODO add your handling code here:
        if(btn_konfigurasi.getText().equalsIgnoreCase("EDIT")){
            editKonfigurasi(true);
            host.requestFocus();
            btn_konfigurasi.setText("SIMPAN");
        }else if (btn_konfigurasi.getText().equalsIgnoreCase("SIMPAN")){
            simpanKonfigurasi();
            editKonfigurasi(false);
            JOptionPane.showMessageDialog(null, "Konfigurasi Berhasil Disimpan");
            btn_konfigurasi.setText("EDIT");
            
        }
    }//GEN-LAST:event_btn_konfigurasiActionPerformed

    private void backupDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupDBActionPerformed
        // TODO add your handling code here:
        new backupView().setVisible(true);
    }//GEN-LAST:event_backupDBActionPerformed

    private void restoreDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreDBActionPerformed
        // TODO add your handling code here:
        new restoreView().setVisible(true);
    }//GEN-LAST:event_restoreDBActionPerformed

    private void teskoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teskoneksiActionPerformed
        // TODO add your handling code here:
        new tesKoneksi().getConnection();
    }//GEN-LAST:event_teskoneksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new awalView().setVisible(true);
            }
        });
    }

    public JLabel getIsibagian() {
        return isibagian;
    }

    public JLabel getIsinama() {
        return isinama;
    }

    public JLabel getIsinip() {
        return isinip;
    }

    public JMenu getMenu1() {
        return menu1;
    }

    public JMenu getMenu2() {
        return menu2;
    }

    public JMenu getMenu3() {
        return laporan;
    }

    public JMenu getMenu4() {
        return menu4;
    }

    public JMenuItem getBackupDB() {
        return backupDB;
    }

    public JMenuItem getDataBarang() {
        return dataBarang;
    }

    public JMenuItem getDataPegawai() {
        return dataPegawai;
    }

    public JMenuItem getDetail_penjualan() {
        return detail_penjualan;
    }

    public JMenuItem getData_user() {
        return data_user;
    }

    public JButton getLogin() {
        return login;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem backupDB;
    private javax.swing.JMenuItem barang;
    private javax.swing.JButton btn_konfigurasi;
    private javax.swing.JMenuItem dataBarang;
    private javax.swing.JMenuItem dataPegawai;
    private javax.swing.JMenuItem data_user;
    private javax.swing.JTextField database;
    private javax.swing.JMenuItem detail_penjualan;
    private javax.swing.JTextField host;
    private javax.swing.JLabel isibagian;
    private javax.swing.JLabel isinama;
    private javax.swing.JLabel isinip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanPegawai;
    private javax.swing.JMenuItem laporanPenjualan;
    private javax.swing.JMenuItem laporanUser;
    private javax.swing.JButton login;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenu menu4;
    private javax.swing.JTextField password;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JTextField port;
    private javax.swing.JMenuItem restoreDB;
    private javax.swing.JLabel tanggal;
    private javax.swing.JButton teskoneksi;
    private javax.swing.JTextField username;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
